package it.unibo;

import it.unibo.controller.Controller;

public class App {
    public static void main(String[] args) {
        new Controller().goToMenu();
    }
}
// BISOGNA SISTEMARE GESTIONE DATI CLIENTE, MODIFICANDO TUTTI I LOCALDATE IN DATE DI SQL
// SISTEMARE GLI INSERIMENTI COME FATTO IN CLIENTE, PERCHE SONO AUTO INCREMENT
// HO CAMBIATO IL DB STATO ORDINE, BISOGNA IN DBMAIN SISTEMARE IL NUOVO SCHEMA LOGICO CHIAMATO CORRETTO.
// DOPO CHIEDERE A CHAT LA RICHIESTA NEL FILE TXT NEL DESKTOP.