package it.unibo;

import it.unibo.controller.Controller;

public class App {
    public static void main(String[] args) {
        new Controller().goToMenu();
    }
}
// BISOGNA SISTEMARE GESTIONE DATI CLIENTE, MODIFICANDO TUTTI I LOCALDATE IN DATE DI SQL
// SISTEMARE GLI INSERIMENTI COME FATTO IN CLIENTE, PERCHE SONO AUTO INCREMENT
// BISOGNA GESTIRE GLI ORDINI, BISOGNA GESTIRE IL FATTO CHE IL CODICE RIDER IN STATO ORDINE ALL'INIZIO NO  è PRESENTE